name: CI/CD Pipeline for Book Spot

on:
  push:
    branches:
      - main  # Déclencher le déploiement lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v2

    - name: Configurer SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copier les fichiers via SSH
      run: |
        # Copier les fichiers vers le serveur via SCP
        scp -r ./* ladjini@192.168.1.86:/c/Users/Ladjini/Desktop/Project-Final-CDA/

    - name: Redémarrer le service Spring Boot via PowerShell
      run: |
        # Arrêter le processus Java Spring Boot (si lancé via `java -jar`)
        ssh ladjini@192.168.1.86 "powershell.exe Stop-Process -Name java -Force"
        # Redémarrer le service Spring Boot (lancez à nouveau le fichier JAR)
        ssh ladjini@192.168.1.86 "start /B java -jar C:/Users/Ladjini/Desktop/Project-Final-CDA/spring-boot-app.jar"

    - name: Redémarrer le service React (si utilisé avec PM2)
      run: |
        # Si vous utilisez PM2 pour gérer l'application React
        ssh ladjini@192.168.1.86 "pm2 restart react-app"
