name: CI/CD Pipeline for Book Spot

on:
  push:
    branches:
      - main  # Déclencher le déploiement lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Version stable d'Ubuntu

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v2  # Récupérer le code source

    - name: Mettre à jour OpenSSH et OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client openssl  # Installer OpenSSH et OpenSSL si nécessaire

    - name: Configurer SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Utiliser la clé SSH stockée dans GitHub Secrets

    - name: Tester la connexion SSH
      run: |
        ssh -o StrictHostKeyChecking=no ladjini@192.168.1.86 "echo 'SSH connexion réussie!'"  # Tester la connexion SSH

    - name: Copier les fichiers vers le serveur via SCP
      run: |
        scp -r ./ ladjini@192.168.1.86:/mnt/c/Users/Ladjini/Desktop/Project-Final-CDA/  # Copier les fichiers via SCP en utilisant un chemin compatible Linux

    - name: Redémarrer l'application via Docker Compose
      run: |
        # Connecter au serveur via SSH et redémarrer les services Docker
        ssh ladjini@192.168.1.86 "
          cd /mnt/c/Users/Ladjini/Desktop/Project-Final-CDA/ && \
          docker-compose down && \
          docker-compose up -d
        "  # Utilisation de docker-compose pour redémarrer l'application
