name: CI/CD Pipeline for Book Spot

on:
  push:
    branches:
      - main  # Déclencher le déploiement lors d'un push sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Version stable d'Ubuntu

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v2

    - name: Mettre à jour OpenSSH et OpenSSL
      run: |
        sudo apt-get update
        sudo apt-get install openssh-client openssl

    - name: Configurer SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Tester la connexion SSH
      run: |
        ssh -o StrictHostKeyChecking=no ladjini@192.168.1.86 "echo 'SSH connexion réussie!'"

    - name: Copier les fichiers vers le serveur via SCP
      run: |
        scp -r ./* ladjini@192.168.1.86:"/C:/Users/Ladjini/Desktop/Project-Final-CDA/"

    - name: Redémarrer le serveur
      run: |
        ssh ladjini@192.168.1.86 "cd /C:/Users/Ladjini/Desktop/Project-Final-CDA/ && ./restart_script.sh"
